// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: bgp.proto

package bpg

import (
	context "context"
	common "github.com/ohanan/bpg/pkg/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BpgClient is the client API for Bpg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BpgClient interface {
	SayHello(ctx context.Context, in *common.HelloRequest, opts ...grpc.CallOption) (*common.HelloReply, error)
}

type bpgClient struct {
	cc grpc.ClientConnInterface
}

func NewBpgClient(cc grpc.ClientConnInterface) BpgClient {
	return &bpgClient{cc}
}

func (c *bpgClient) SayHello(ctx context.Context, in *common.HelloRequest, opts ...grpc.CallOption) (*common.HelloReply, error) {
	out := new(common.HelloReply)
	err := c.cc.Invoke(ctx, "/bpg.Bpg/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BpgServer is the server API for Bpg service.
// All implementations must embed UnimplementedBpgServer
// for forward compatibility
type BpgServer interface {
	SayHello(context.Context, *common.HelloRequest) (*common.HelloReply, error)
	mustEmbedUnimplementedBpgServer()
}

// UnimplementedBpgServer must be embedded to have forward compatible implementations.
type UnimplementedBpgServer struct {
}

func (UnimplementedBpgServer) SayHello(context.Context, *common.HelloRequest) (*common.HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedBpgServer) mustEmbedUnimplementedBpgServer() {}

// UnsafeBpgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BpgServer will
// result in compilation errors.
type UnsafeBpgServer interface {
	mustEmbedUnimplementedBpgServer()
}

func RegisterBpgServer(s grpc.ServiceRegistrar, srv BpgServer) {
	s.RegisterService(&Bpg_ServiceDesc, srv)
}

func _Bpg_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BpgServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bpg.Bpg/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BpgServer).SayHello(ctx, req.(*common.HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bpg_ServiceDesc is the grpc.ServiceDesc for Bpg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bpg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bpg.Bpg",
	HandlerType: (*BpgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Bpg_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bgp.proto",
}
